[package]
name = "promptress"
version = "0.1.0"
authors = ["Jasmine Tai <jtai@jtai.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.5"
users = "0.9"
smallvec = "0.6"
termion = "1"
git2 = { version = "0.9", default-features = false }
